import { createRoot } from "react-dom/client";
import "./index.css";
import i18n from "i18next";
import App from "./App.tsx";
import { initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
	resources: {
		en: {
			translation: {
				Welcome: "Welcome Adventurer!! I've been waiting for you",
				Title: "Learn Python",
				Title1: "Interactive Lessons",
				Title2: "Multiple Choice Quizzes",
				Title3: "Built-in Code Editor",
				Description:
					"Explore Python in a simple, interactive, and friendly way.",
				Description1: "Learn Python with simple step-by-step explanations.",
				Description2: "Test your knowledge with quick quiz questions.",
				Description3: "Write and run Python code in your browser.",
				Module: "Module",
				ButtonText: "Enjoy Լearning",
				AboutTitle:
					"Interactive Python Learning Platform",
				AboutDesc:
					"Glione is a Python learning website that helps beginners learn programming through interactive lessons, quizzes, and hands-on coding practice. The platform combines theory and practical exercises to create an engaging learning experience.",
				AboutQuestion: "What is Glione?",
				AboutDesc1:
					"Glione is an educational web application designed to make learning Python simple and interactive. Users can study structured lessons, answer multiple-choice questions to test their understanding, and practice coding directly in the built-in code editor. Our goal is to help learners improve their programming skills in a fun and effective way.",
				NavbarHome: "Home",
				NavbarAbout: "About",
				NavbarCourses: "Courses",
				NavbarPricing: "Pricing",
				GetStarted: "Get Started",
				Signin: "Sign in",
				FooterPrivacy: "Privacy Policy",
				PriceCardTitle: "Starter",
				PriceCardTitle1: "Pro",
				PriceCardTitle2: "Master",
				PriceCardDescription:
					"Perfect for beginners who want to explore Python fundamentals at their own pace.",
				PriceCardDescription1:
					"For serious learners who want structured paths, real-world projects, and faster progress.",
				PriceCardDescription2:
					"Advanced training designed to prepare you for professional Python development roles.",
				PriceCardPrice: "For Free",
				PriceCardButton: "Your current plan",
				PriceCardButton1: "Continue",
				PriceCardFeatureTitle: "Everything in Starter includes:",
				PriceCardFeatureTitle1: "Everything in Pro includes:",
				PriceCardFeatureTitle2: "Everything in Master includes:",
				PriceCardFeature: "Access to beginner lessons",
				PriceCardFeature1: "Interactive coding exercises",
				PriceCardFeature2: "Community support",
				PriceCardFeature3: "10 practice challenges",
				PriceCardFeature4: "Progress tracking",
				PriceCardFeature5: "Everything in Starter",
				PriceCardFeature6: "Full access to all courses",
				PriceCardFeature7: "Real-world Python projects",
				PriceCardFeature8: "Unlimited practice challenges",
				PriceCardFeature9: "Priority Support",
				PriceCardFeature10: "Everything in Pro",
				PriceCardFeature11: "Career-focused learning tracks",
				PriceCardFeature12: "1-on-1 mentor sessions",
				PriceCardFeature13: "Portfolio review",
				PriceCardFeature14: "Advanced topics (AI, Web, Automation)",
				SignInWelcome: "Welcome Back!",
				SignInEmail: "Email",
				SignInPassword: "Password",
				SignInButton: "Log In",
				SignInText: "Don't have an account?",
				SignInSignUp: "Sign Up",
				SignInWithGoogle: "Log in with",
				SignInOr: "or",
				SignInRightPageText:
					"Welcome to our Python learning project powered by Medusa.",
				SignInRightPageText1:
					"Learn Python through simple lessons and hands-on practice.",
				SignUpConfirmPassword: "Confirm Password",
				SignUpButton: "Sign Up",
				SignUpText: "Already have an account?",
				SignUpLogIn: "Log In",
				SignUpWelcome: "Create an Account!",
				Previous: "Previous",
				Next: "Next",
				Check: "Check",
				Complete: "Complete",
				DoubleClickToEdit: "Double click to edit",
				Content: "Content",
				Ok: "OK",
				Add: "Add",
				Sumbit: "Submit",
				AdminDescription: "Description",
				AdminTitle: "Title",
				Continue: "Continue",
				Tag: "Tag",
				CheckItOut: "Check it out",
				TryAgain: "Try Again",
				Success: "Success",
				SuccessText: "Lesson is created successfully. Good Luck!",
				MessageError: "Error",
				MessageErrorText: "Lesson is not created. Please try again.",
				Streak: "Streak",
				Finished: "Finished Lessons",
				DailyFinished: "Daily Finished Lessons",
				Energy: "Energy",
				CompletedLessons: "Completed Lessons",
				YourProgress: "Your Progress",
				WeeklyProgress: "Weekly Progress",
				Completed: "Completed",
				Pending: "Pending",
				Sunday: "Sun",
				Monday: "Mon",
				Tuesday: "Tue",
				Wednesday: "Wed",
				Thursday: "Thu",
				Friday: "Fri",
				Saturday: "Sat",
				MyProfile: "My Profile",
				DashboardText: "Learn Python, challenge your mind, and build skills.",
			},
		},
		am: {
			translation: {
				Welcome: "Բարի գալուստ",
				Title: "Սովորիր Python",
				Title1: "Ինտերակտիվ Դասեր",
				Title2: "Բազմակի Ընտրությամբ Թեստեր",
				Title3: "Ներկառուցված Կոդի Խմբագիր",
				Description: "Բացահայտիր Python-ը պարզ, ինտերակտիվ և հարմար ձևով։",
				Description1:
					"Սովորիր Python-ը պարզ քայլ առ քայլ բացատրություններով։",
				Description2: "Ստուգիր գիտելիքներդ արագ թեստային հարցերով։",
				Description3: "Գրիր և գործարկիր Python կոդ անմիջապես բրաուզերում։",
				Module: "Մոդուլ",
				ButtonText: "Վայելիր սովորելը",
				AboutTitle:
					"Ինտերակտիվ Python ուսուցման հարթակ",
				AboutDesc:
					"«Glione-ը Python ուսուցման կայք է, որը օգնում է սկսնակներին սովորել ծրագրավորում ինտերակտիվ դասերի, թեստերի և գործնական կոդավորման միջոցով։ Հարթակը համատեղում է տեսական և գործնական ուսուցումը՝ ապահովելով հետաքրքիր և արդյունավետ ուսուցման փորձ։",
				AboutQuestion: "Ինչ է «Glione»-ը",
				AboutDesc1:
					"Glione-ը կրթական վեբ հավելված է, որը ստեղծվել է Python ծրագրավորման ուսուցումը հեշտ և ինտերակտիվ դարձնելու համար։ Օգտատերերը կարող են ուսումնասիրել կառուցվածքային դասեր, պատասխանել բազմակի ընտրությամբ հարցերի՝ իրենց գիտելիքները ստուգելու համար, և գրել ու փորձարկել Python կոդ ներկառուցված կոդի խմբագրիչում։ Մեր նպատակն է օգնել սովորողներին զարգացնել ծրագրավորման հմտությունները հետաքրքիր և արդյունավետ ձևով։",
				NavbarHome: "Գլխավոր էջ",
				NavbarAbout: "Մեր մասին",
				NavbarCourses: "Դասընթացներ",
				NavbarPricing: "Արժեքներ",
				GetStarted: "Սկսել",
				Signin: "Մուտք գործել",
				FooterPrivacy: "Գաղտնիության քաղաքականություն",
				PriceCardTitle: "Սկսնակ",
				PriceCardTitle1: "Պրոֆեսիոնալ",
				PriceCardTitle2: "Մաստեր",
				PriceCardDescription:
					"Հիանալի է սկսնակների համար, ովքեր ցանկանում են ուսումնասիրել Python-ի հիմունքները իրենց սեփական տեմպով։",
				PriceCardDescription1:
					"Լուրջ սովորողների համար, ովքեր ցանկանում են կառուցվածքային ուղիներ, իրական աշխարհի նախագծեր և ավելի արագ առաջընթաց։",
				PriceCardDescription2:
					"Առաջադեմ դասընթաց, որը նախատեսված է ձեզ Python-ի մասնագիտական ​​​​մշակման դերերի պատրաստելու համար։",
				PriceCardPrice: "Անվճար",
				PriceCardButton: "Ձեր ընթացիկ պլանը",
				PriceCardButton1: "Շարունակել",
				PriceCardFeatureTitle: "«Սկսնակ»-ը ներառում է՝",
				PriceCardFeatureTitle1: "«Պրոֆեսիոնալ»-ը ներառում է՝",
				PriceCardFeatureTitle2: "«Մաստեր»-ը ներառում է՝",
				PriceCardFeature: "«Հասանելիություն սկսնակների դասերին»",
				PriceCardFeature1: "«Ինտերակտիվ կոդավորման վարժություններ»",
				PriceCardFeature2: "«Համայնքի աջակցություն»",
				PriceCardFeature3: "«10 գործնական մարտահրավեր»",
				PriceCardFeature4: "«Առաջընթացի հետևում»",
				PriceCardFeature5: "«Ամեն ինչ «Սկսնակ»-ում»",
				PriceCardFeature6: "«Լիարժեք մուտք բոլոր դասընթացներին»",
				PriceCardFeature7: "«Իրական Python նախագծեր»",
				PriceCardFeature8: "«Անսահմանափակ պրակտիկայի մարտահրավերներ»",
				PriceCardFeature9: "«Առաջնահերթ աջակցություն»",
				PriceCardFeature10: "«Ամեն ինչ «Պրոֆեսիոնալ»-ում»",
				PriceCardFeature11: "«Կարիերայի վրա կենտրոնացած ուսուցման ուղիներ»",
				PriceCardFeature12: "«Անհատական ​​մենթորական հանդիպումներ»",
				PriceCardFeature13: "«Պորտֆոլիոյի վերանայում»",
				PriceCardFeature14: "«Ավելի բարդ թեմաներ (AI, Web, Automation)»",
				SignInWelcome: "Բարի՜ Վերադարձ",
				SignInEmail: "Էլ. հասցե",
				SignInPassword: "Գաղտնաբառ",
				SignInButton: "Մուտք Գործել",
				SignInText: "Գրանցված չե՞ք։ Դե բա",
				SignInSignUp: "գրանցվեք:",
				SignInWithGoogle: "Մուտք գործել",
				SignInOr: "կամ",
				SignInRightPageText:
					"Բարի գալուստ մեր Python ուսուցման նախագիծ՝ Մեդուզայի կողմից։",
				SignInRightPageText1:
					"Սովորեք Python՝ պարզ դասերի և գործնական պարապմունքների միջոցով։",
				SignUpConfirmPassword: "Հաստատել Գաղտնաբառը",
				SignUpButton: "Գրանցվել",
				SignUpText: "Արդեն գրանցված ե՞ք: Դե բա",
				SignUpLogIn: "մուտք գործեք:",
				SignUpWelcome: "Ստեղծեք Օգտահաշիվ",
				Previous: "Նախորդ էջ",
				Next: "Հաջորդ էջ",
				Check: "Ստուգել",
				Complete: "Ավարտել",
				DoubleClickToEdit: "Սեղմեք 2 անգամ՝ փոփոխելու համար",
				Content: "Բովանդակություն",
				Ok: "Lավ",
				Add: "Ավելացնել",
				Submit: "Հաստատել",
				AdminDescription: "Նկարագրություն",
				AdminTitle: "Վերնագիր",
				Continue: "Շարունակել",
				Tag: "Թեգ",
				CheckItOut: "Ստուգել",
				TryAgain: "Փորձել կրկին",
				Success: "Հաջողված է",
				SuccessText: "Դասը հաջողությամբ ստեղծվել է:",
				MessageError: "Սխալ",
				MessageErrorText: "Դասը չի ստեղծվել: Փորձեք կրկին:",
				Streak: "Օր անընդմեջ",
				Finished: "Ավարտված դասեր",
				DailyFinished: "Օրական ավարտված դասեր",
				Energy: "Էներգիա",
				CompletedLessons: "Ավարտած դասեր",
				YourProgress: "Ձեր Առաջընթացը",
				WeeklyProgress: "Շաբաթական Առաջընթաց",
				Completed: "Կատարված",
				Pending: "Ընթացքի մեջ",
				Sunday: "Կիր",
				Monday: "Երկ",
				Tuesday: "Երք",
				Wednesday: "Չոր",
				Thursday: "Հին",
				Friday: "Ուրբ",
				Saturday: "Շաբ",
				MyProfile: "Իմ Պրոֆիլը",
				DashboardText: "Սովորիր Python, մարտահրավեր նետիր մտքիդ և զարգացրու հմտություններ։",
			},
		},
	},
	lng: "en",
	fallbackLng: "en",

	interpolation: {
		escapeValue: false,
	},
});

createRoot(document.getElementById("root")!).render(<App />);
