import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import i18n from "i18next";
import App from "./App.tsx";
import { initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
	resources: {
		en: {
			translation: {
				Welcome: "Welcome Adventurer!! I've been waiting for you",
				Title: "Learn Python",
				Title1: "Games with Python",
				Title2: "Programming with Python",
				Title3: "Interesting lessons",
				Description: "Learn Python with us the fun way",
				Description1: "Create games with Python",
				Description2: "Create apps using Python",
				Description3: "Learning Python in interesting way",
				Module: "Module",
				ButtonText: "View details",
				AboutTitle:
					"Venture into the depths. Conquer the code. Master Python.",
				AboutDesc:
					"Glione is an interactive Python and Computer Science learning platform where every lesson is a dungeon, every challange is a monster.",
				AboutQuestion: "What is Glione?",
				AboutDesc1:
					"Glione turns learning Python into an adventure. Instead of dry tutorials you explore dungoens, slaying monsters. Solve coding challenges to defeat enemies, collect loot, and level up your character as your real-world skills grow.",
				NavbarHome: "Home",
				NavbarAbout: "About",
				NavbarCourses: "Courses",
				NavbarPricing: "Pricing",
				GetStarted: "Get Started",
				Signin: "Sign in",
				FooterPrivacy: "Privacy Policy",
				PriceCardTitle: "Starter",
				PriceCardTitle1: "Pro",
				PriceCardTitle2: "Master",
				PriceCardDescription:
					"Perfect for beginners who want to explore Python fundamentals at their own pace.",
				PriceCardDescription1:
					"For serious learners who want structured paths, real-world projects, and faster progress.",
				PriceCardDescription2:
					"Advanced training designed to prepare you for professional Python development roles.",
				PriceCardPrice: "For Free",
				PriceCardButton: "Your current plan",
				PriceCardButton1: "Continue",
				PriceCardFeatureTitle: "Everything in Starter includes:",
				PriceCardFeatureTitle1: "Everything in Pro includes:",
				PriceCardFeatureTitle2: "Everything in Master includes:",
				PriceCardFeature: "Access to beginner lessons",
				PriceCardFeature1: "Interactive coding exercises",
				PriceCardFeature2: "Community support",
				PriceCardFeature3: "10 practice challenges",
				PriceCardFeature4: "Progress tracking",
				PriceCardFeature5: "Everything in Starter",
				PriceCardFeature6: "Full access to all courses",
				PriceCardFeature7: "Real-world Python projects",
				PriceCardFeature8: "Unlimited practice challenges",
				PriceCardFeature9: "Priority Support",
				PriceCardFeature10: "Everything in Pro",
				PriceCardFeature11: "Career-focused learning tracks",
				PriceCardFeature12: "1-on-1 mentor sessions",
				PriceCardFeature13: "Portfolio review",
				PriceCardFeature14: "Advanced topics (AI, Web, Automation)",
				SignInWelcome: "Welcome Back!",
				SignInEmail: "Email",
				SignInPassword: "Password",
				SignInButton: "Log In",
				SignInText: "Don't have an account?",
				SignInSignUp: "Sign Up",
				SignInWithGoogle: "Log in with",
				SignInOr: "or",
				SignInRightPageText:
					"Welcome to our Python learning project powered by Medusa.",
				SignInRightPageText1:
					"Learn Python through simple lessons and hands-on practice.",
				SignUpConfirmPassword: "Confirm Password",
				SignUpButton: "Sign Up",
				SignUpText: "Already have an account?",
				SignUpLogIn: "Log In",
				SignUpWelcome: "Create an Account!",
				Previous: "Previous",
				Next: "Next",
				Check: "Check",
				Complete: "Complete",
				DoubleClickToEdit: "Double click to edit",
				Content: "content",
				Ok: "OK",
				Add: "Add",
				Sumbit: "Submit",
				AdminDescription: "Description",
				AdminTitle: "Title",
				Continue: "Continue",
				Tag: "Tag",
				CheckItOut: "Check it out",
				TryAgain: "Try Again",
				Success: "Success",
				SuccessText: "Lesson is created successfully. Good Luck!",
				MessageError: "Error",
				MessageErrorText: "Lesson is not created. Please try again.",
				Streak: "Streak",
				Finished: "Finished Lessons",
				DailyFinished: "Daily Finished Lessons",
				AvgScore: "Average Score",
				HoursLearned: "Hours Learned",
				YourProgress: "Your Progress",
				WeeklyProgress: "Weekly Progress",
				Completed: "Completed",
				Pending: "Pending",
				Sunday: "Sun",
				Monday: "Mon",
				Tuesday: "Tue",
				Wednesday: "Wed",
				Thursday: "Thu",
				Friday: "Fri",
				Saturday: "Sat",
				MyProfile: "My Profile",
				DashboardText: "Be your best version",
			},
		},
		am: {
			translation: {
				Welcome: "Բարի գալուստ",
				Title: "Սովորիր Python",
				Title1: "Python Խաղեր",
				Title2: "Ծրագրավորում Python-ով",
				Title3: "Հետաքրքիր դասեր",
				Description: "Սովորիր մեզ հետ Python զվարճալի ձևով",
				Description1: "Ստեղծիր խաղեր օգտագործելով Python",
				Description2: "Ստեղծիր ծրագրեր օգտագործելով Python",
				Description3: "Սովորիր Python հետաքրքիր ձևով",
				Module: "Մոդուլ",
				ButtonText: "Տեսնել ավելին",
				AboutTitle:
					"Սուզվիր խորքերը։ Հաղթահարիր կոդը։ Տիրապետիր Python-ին։",
				AboutDesc:
					"«Glione»-ը ինտերակտիվ Python-ի և համակարգչային գիտության ուսուցման հարթակ է, որտեղ ամեն դաս մի զնդան է, իսկ ամեն մարտահրավեր՝ հրեշ, որը պետք է հաղթահարես։",
				AboutQuestion: "Ինչ է «Glione»-ը",
				AboutDesc1:
					"«Glione»-ը Python սովորելը վերածում է արկածի։ Չոր ու ձանձրալի ձեռնարկների փոխարեն դու ուսումնասիրում ես զնդաններ և կռվում հրեշների դեմ։ Լուծիր ծրագրավորման խնդիրներ՝ թշնամիներին հաղթելու համար, հավաքիր ավար և զարգացրու քո կերպարը, մինչ քո իրական հմտություններն էլ աճում են։",
				NavbarHome: "Գլխավոր էջ",
				NavbarAbout: "Մեր մասին",
				NavbarCourses: "Դասընթացներ",
				NavbarPricing: "Արժեքներ",
				GetStarted: "Սկսել",
				Signin: "Մուտք գործել",
				FooterPrivacy: "Գաղտնիության քաղաքականություն",
				PriceCardTitle: "Սկսնակ",
				PriceCardTitle1: "Պրոֆեսիոնալ",
				PriceCardTitle2: "Մաստեր",
				PriceCardDescription:
					"Հիանալի է սկսնակների համար, ովքեր ցանկանում են ուսումնասիրել Python-ի հիմունքները իրենց սեփական տեմպով։",
				PriceCardDescription1:
					"Լուրջ սովորողների համար, ովքեր ցանկանում են կառուցվածքային ուղիներ, իրական աշխարհի նախագծեր և ավելի արագ առաջընթաց։",
				PriceCardDescription2:
					"Առաջադեմ դասընթաց, որը նախատեսված է ձեզ Python-ի մասնագիտական ​​​​մշակման դերերի պատրաստելու համար։",
				PriceCardPrice: "Անվճար",
				PriceCardButton: "Ձեր ընթացիկ պլանը",
				PriceCardButton1: "Շարունակել",
				PriceCardFeatureTitle: "«Սկսնակ»-ը ներառում է՝",
				PriceCardFeatureTitle1: "«Պրոֆեսիոնալ»-ը ներառում է՝",
				PriceCardFeatureTitle2: "«Մաստեր»-ը ներառում է՝",
				PriceCardFeature: "«Հասանելիություն սկսնակների դասերին»",
				PriceCardFeature1: "«Ինտերակտիվ կոդավորման վարժություններ»",
				PriceCardFeature2: "«Համայնքի աջակցություն»",
				PriceCardFeature3: "«10 գործնական մարտահրավեր»",
				PriceCardFeature4: "«Առաջընթացի հետևում»",
				PriceCardFeature5: "«Ամեն ինչ «Սկսնակ»-ում»",
				PriceCardFeature6: "«Լիարժեք մուտք բոլոր դասընթացներին»",
				PriceCardFeature7: "«Իրական Python նախագծեր»",
				PriceCardFeature8: "«Անսահմանափակ պրակտիկայի մարտահրավերներ»",
				PriceCardFeature9: "«Առաջնահերթ աջակցություն»",
				PriceCardFeature10: "«Ամեն ինչ «Պրոֆեսիոնալ»-ում»",
				PriceCardFeature11: "«Կարիերայի վրա կենտրոնացած ուսուցման ուղիներ»",
				PriceCardFeature12: "«Անհատական ​​մենթորական հանդիպումներ»",
				PriceCardFeature13: "«Պորտֆոլիոյի վերանայում»",
				PriceCardFeature14: "«Ավելի բարդ թեմաներ (AI, Web, Automation)»",
				SignInWelcome: "Բարի՜ Վերադարձ",
				SignInEmail: "Էլ. հասցե",
				SignInPassword: "Գաղտնաբառ",
				SignInButton: "Մուտք Գործել",
				SignInText: "Գրանցված չե՞ք։ Դե բա",
				SignInSignUp: "գրանցվեք:",
				SignInWithGoogle: "Մուտք գործել",
				SignInOr: "կամ",
				SignInRightPageText:
					"Բարի գալուստ մեր Python ուսուցման նախագիծ՝ Մեդուզայի կողմից։",
				SignInRightPageText1:
					"Սովորեք Python՝ պարզ դասերի և գործնական պարապմունքների միջոցով։",
				SignUpConfirmPassword: "Հաստատել Գաղտնաբառը",
				SignUpButton: "Գրանցվել",
				SignUpText: "Արդեն գրանցված ե՞ք: Դե բա",
				SignUpLogIn: "մուտք գործեք:",
				SignUpWelcome: "Ստեղծեք Օգտահաշիվ",
				Previous: "Նախորդ էջ",
				Next: "Հաջորդ էջ",
				Check: "Ստուգել",
				Complete: "Ավարտել",
				DoubleClickToEdit: "Սեղմեք 2 անգամ՝ փոփոխելու համար",
				Content: "Բովանդակություն",
				Ok: "Lավ",
				Add: "Ավելացնել",
				Submit: "Հաստատել",
				AdminDescription: "Նկարագրություն",
				AdminTitle: "Վերնագիր",
				Continue: "Շարունակել",
				Tag: "Թեգ",
				CheckItOut: "Ստուգել",
				TryAgain: "Փորձել կրկին",
				Success: "Հաջողված է",
				SuccessText: "Դասը հաջողությամբ ստեղծվել է:",
				MessageError: "Սխալ",
				MessageErrorText: "Դասը չի ստեղծվել: Փորձեք կրկին:",
				Streak: "Օր անընդմեջ",
				Finished: "Ավարտված դասեր",
				DailyFinished: "Օրական ավարտված դասեր",
				AvgScore: "Միջին միավոր",
				HoursLearned: "Սովորած ժամեր",
				YourProgress: "Ձեր Առաջընթացը",
				WeeklyProgress: "Շաբաթական Առաջընթաց",
				Completed: "Կատարված",
				Pending: "Ընթացքի մեջ",
				Sunday: "Կիր",
				Monday: "Երկ",
				Tuesday: "Երք",
				Wednesday: "Չոր",
				Thursday: "Հին",
				Friday: "Ուրբ",
				Saturday: "Շաբ",
				MyProfile: "Իմ Պրոֆիլը",
				DashboardText: "Եղիր քո լավագույն տարբերակը",
			},
		},
	},
	lng: "en",
	fallbackLng: "en",

	interpolation: {
		escapeValue: false,
	},
});

createRoot(document.getElementById("root")!).render(
	<App />,
);
